# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TripPlanner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestRNGP

  pod 'GoogleMaps'
  pod 'GooglePlaces' 
  pod 'GooglePlacePicker'

  #pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

end

